name: Tests
on:
  workflow_dispatch:
  workflow_call:
  push:
    branches:
      - "main"
    paths-ignore:
      - "terraform/**"
  pull_request:
    branches:
      - "*"
    paths-ignore:
      - "terraform/**"

jobs:
  unit-test:
    name: Unit tests
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Install dependencies
        run: python -m pip install tox

      - name: Run tests
        run: tox -e unit

  integration-test-microk8s:
    name: Integration tests (microk8s)
    runs-on: ubuntu-24.04
    timeout-minutes: 900
    needs:
      - unit-test
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Setup operator environment
        uses: charmed-kubernetes/actions-operator@main
        with:
          provider: microk8s
          channel: 1.31-strict/stable
          juju-channel: 3.6

      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
        with:
          detached: true
          sudo: true
